# 混合ロジットモデルの限界効果計算の例
# generated by ChatGPT on 2025-11-09
# modified by 8-u8
library(mlogit)
library(gmnl)

# 元データ
df <- data.frame(
  id = rep(1:4, each=3),
  mode = rep(c("car", "bus", "train"), times=4),
  choice = c(1,0,0, 0,1,0, 0,0,1, 1,0,0),
  time = c(30,45,50, 40,30,60, 50,55,35, 35,50,45),
  cost = c(400,200,500, 450,180,550, 500,220,480, 350,210,530)
)

# 個人属性（個体水準データ）
income <- data.frame(
  id = 1:4,
  income = c(300, 500, 450, 350)  # 適当な年収例
)

# 結合
df <- merge(df, income, by="id")

# mlogit形式に変換
mdata <- mlogit.data(df, choice="choice", shape="long", alt.var="mode", id.var="id")

# 混合ロジット（ランダム係数モデル）
mix_model <- gmnl(
  formula = choice ~ time + cost | 0 | income,  # timeとcostは代替特有属性
  data = mdata,
  model = "mixl",
  ranp = c(cost = "n"),  # cost の係数を正規分布とする
  R = 200,               # シミュレーション回数（実務は1000〜2000）
  halton = NA            # ハルトン列 → シミュレーション誤差が少ない
)

summary(mix_model)

pred <- fitted(mix_model, outcome = FALSE)
head(pred)


# costを1単位増やしたときの限界効果を数値的に計算
df2 <- df
df2$cost <- df2$cost + 1
mdata2 <- mlogit.data(df2, choice="choice", shape="long", alt.var="mode", id.var="id")

# 元のデータでの予測確率
pred0 <- fitted(mix_model, outcome = FALSE)

# cost+1のデータで予測確率を計算（手動で計算）
# 係数を取得
coef_est <- coef(mix_model)

#' 効用関数を計算する関数
#'
#' @description
#' この関数は、混合ロジットモデルにおける効用値を計算します。
#' 選択肢の属性と個人固有のパラメータに基づいて効用を算出します。
#'
#' @param data_mlogit mlogit用のlongデータフレーム
#' @param coefs 推定されたモデルの係数（名前付きベクトル）
#'
#' @return 計算された効用値
#'
#' @examples
#' # 例: 効用関数の計算
#' attributes <- c(price = 100, quality = 5)
#' parameters <- c(price = -0.5, quality = 1.2)
#' utility <- compute_utility(attributes, parameters)
#'
#' @export
# 効用関数を計算する関数
calc_prob <- function(data_mlogit, coefs) {
  
  time_val <- data_mlogit$time |> as.numeric()
  cost_val <- data_mlogit$cost |> as.numeric()
  income_val <- data_mlogit$income |> as.numeric()
  
  # 基本効用（平均）- 係数名を正しく取得
  beta_time <- coefs["time"] |> as.numeric()
  beta_cost <- coefs["cost"] |>as.numeric()
  # income係数は代替交通手段ごとに存在する
  beta_income_bus <- coefs["income:bus"] |> as.numeric()
  beta_income_car <- coefs["income:car"] |> as.numeric()
  beta_income_train <- coefs["income:train"] |> as.numeric()
  
  # 各交通手段に対応するincome係数を適用
  mode_val <- as.character(data_mlogit$mode)
  beta_income <- ifelse(mode_val == "bus", beta_income_bus,
                       ifelse(mode_val == "car", beta_income_car,
                              beta_income_train))
  

  V <- beta_time * time_val + beta_cost * cost_val + beta_income * income_val

  
  # 選択肢ごとにグループ化して確率計算
  ids <- as.character(data_mlogit$id)
  
  probs <- rep(NA, length(V))
  for(i in unique(ids)) {
    idx <- which(ids == i)
    exp_V <- exp(V[idx])
    probs[idx] <- exp_V / sum(exp_V)
  }
  
  return(probs)
}

# cost+1での予測確率
pred1 <- calc_prob(mdata2, coef_est)

# 限界効果（確率の変化）
marginal_effect_cost <- pred1 - pred0

# 結果を見やすく整形
result <- data.frame(
  id = df$id,
  mode = df$mode,
  prob_original = pred0,
  prob_cost_plus1 = pred1,
  marginal_effect = marginal_effect_cost
)

print(result)
head(result)
